services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=blogpostdb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=blog_service_user'
    ports:
      - '3306'
